### ISSUE TITLE
editgroups.php broken...

### ISSUE THREAD

**Issue by Super-toad65** [WWXD/WorldWeb-XD#17]
hello, i've installed a testboard and it seems that when i go to the editgroups page, the banned group takes me to http://blargboardomega.rf.gd/bbxd/editgroups/-1, and the normal group does nothing. Url rewriting maybe?

also, the normal group is set to nothing becase of Group ID 0. i'll try to do something

**Comment by maorninja** [comment]
Yeah. Its URL rewritting. Thanks for noticing. Will be fixed soon.

**Comment by Super-toad65** [comment]
Also the whole page is and broken

**Comment by maorninja** [comment]
Okay, this bug happens in Blarg if you allow URL rewritting.
