### ISSUE TITLE
Try writing your own README, maybe?

### ISSUE THREAD

**Issue by StapleButter** [WWXD/WorldWeb-XD#30]
The README is that of Blargboard. Clearly whatever you have there is tremendously superior to Blargboard, so it deserves its own README.

**Comment by maorninja** [comment]
Oh shoot, forgot about this, thanks for reminding me...

With that, I'm also planning to remove the maorninja.h05t.gq Bullshit.

**Comment by Super-toad65** [comment]
i might do that when i have some time

~~shut up staplebutter!~~

**Comment by maorninja** [comment]
@StapleButter Done!

Is this fine? Or do you want me to change it even more?

**Comment by StapleButter** [comment]
looking good.

Super-twat 65 you aren't being funny, quit trying.
