### ISSUE TITLE
why didnt you define the version in common.php instead of hard coding it into index.php

### ISSUE THREAD

**Issue by EzioisAwesome56** [WWXD/WorldWeb-XD#38]
YOu do know that instead of manually writing the version to index.php, you can reuse the BLARG_VERSION from common.php

this is what you use
$layout_credits =
`'<img src="'.resourceLink('img/poweredbybbxd.png').'" style="float: left; margin-right: 3px;">WorldWeb XD 0.0.1 &middot; by MaorNinja322 <a href="'.actionLink('credits').'">et al</a><br>
Based <i>heavily</i> off Blargboard by StapleButter & ABXD by Dirbaio, Kawa & co.<br>';`

and here is what I used for MRS
$layout_credits = 
`'<img src="'.resourceLink('img/poweredbyblarg.png').'" style="float: left; margin-right: 3px;">
<a href="https://github.com/EzioisAwesome56/BlargBoard-MRS" target="_blank">Blargboard '.BLARG_VERSION.'</a> &middot; by EzioisAwesome56<br>
Credits are found <a href="'.BOARD_ROOT.'credits/">here</a><br>';`

and if we look at my common.php, you'll find this
`define('BLARG_VERSION', '1.2.5 MRS');`

So it can take normal text too. I just dont see why you didnt do it like that.

**Comment by maorninja** [comment]
There is literally no difference what-so-ever between a hard-code and a define.
